=== darpa-brass/challenge-problems/Scenarios/VICTORY/Scenario_1/VICTORYConfigurationLanguage.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--  
        UNCLASSIFIED//FOR OFFICIAL USE ONLY
        DISTRIBUTION STATEMENT C
    This document is property of the U.S. Government. Distribution authorized to U.S. Government 
    Agencies and their contractors (date of determination as of February 15, 2018). Other 
    requests for this document shall be referred to the VICTORY Standards Support Office (VSSO).
-->
<!--
    Version = 1.6
    Release Date = 20131031
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:vcl="http://www.victory-standards.org/Schemas/VICTORYConfigurationLanguage.xsd"
    xmlns:vmt="http://www.victory-standards.org/Schemas/VICTORYManagementTypes.xsd"
    xmlns:vst="http://www.victory-standards.org/Schemas/VICTORYSharedTypes.xsd"
    targetNamespace="http://www.victory-standards.org/Schemas/VICTORYConfigurationLanguage.xsd"
    elementFormDefault="qualified" version="1.6">
    <xsd:import namespace="http://www.victory-standards.org/Schemas/VICTORYManagementTypes.xsd"
        schemaLocation="VICTORYManagementTypes.xsd"/>
    <xsd:import namespace="http://www.victory-standards.org/Schemas/VICTORYSharedTypes.xsd"
        schemaLocation="VICTORYSharedTypes.xsd"/>
    <xsd:import namespace="http://www.w3.org/2003/05/soap-envelope"
        schemaLocation="soap-envelope.xsd"/>
    <xsd:element name="VCL">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" name="configItem"
                    type="vcl:configItem_t"/>
                <xsd:element maxOccurs="unbounded" minOccurs="0" name="configGroup"
                    type="vcl:configGroup_t"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="configItem_t">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="configGroup_t">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="configItem"
                type="vcl:configItem_t"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="configGroup"
                type="vcl:configGroup_t"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="vcl_t">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="configItem"
                type="vcl:configItem_t"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="configGroup"
                type="vcl:configGroup_t"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="maturity_t">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Preliminary"/>
            <xsd:enumeration value="Experimental"/>
            <xsd:enumeration value="Proposed Standard"/>
            <xsd:enumeration value="Draft Standard"/>
            <xsd:enumeration value="VICTORY Standard"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="getConfiguration">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType/>
    </xsd:element>
    <xsd:element name="getConfigurationResponse">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="VCL" type="vcl:vcl_t"/>
                <xsd:element name="components" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element maxOccurs="unbounded" name="componentErrors"
                                type="vmt:componentErrors_t"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="setConfiguration">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="VCL" type="vcl:vcl_t">
                    <xsd:annotation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="setConfigurationResponse">
        <xsd:annotation>
            <xsd:appinfo>
                <maturity>Proposed Standard</maturity>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="components">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element maxOccurs="unbounded" name="componentErrors"
                                type="vmt:componentErrors_t"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
<!--    DISTRIBUTION STATEMENT C    -->
<!--    UNCLASSIFIED//FOR OFFICIAL USE ONLY    -->

=== darpa-brass/challenge-problems/Scenarios/VICTORY/Scenario_1/BRASS_Scenario1_AfterAdaptation.xml
<?xml version="1.0" encoding="UTF-8"?>
<vcl:VCL xmlns:vcl="http://www.victory-standards.org/Schemas/VICTORYConfigurationLanguage.xsd"
 xmlns:vmt="http://www.victory-standards.org/Schemas/VICTORYManagementTypes.xsd"
 xmlns:vst="http://www.victory-standards.org/Schemas/VICTORYSharedTypes.xsd"
 xmlns:tns="http://www.w3.org/2003/05/soap-envelope"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.victory-standards.org/Schemas/VICTORYConfigurationLanguage.xsd 
 ./VICTORYConfigurationLanguage.xsd">
    <vcl:configGroup type="SHARED_PROCESSING_UNIT" name="NewSharedProcessingUnit">
        <vcl:configItem name="announcementEnabled" value="true"/>
        <vcl:configGroup type="SHARED_PROCESSING_UNIT" name="soapComponent">
            <vcl:configGroup name="services">
                <vcl:configGroup name="service">
                    <vcl:configItem name="uniqueName" value="DataLoggerService"/>
                    <vcl:configItem name="startService" value="false"/>
                    <vcl:configGroup name="victoryComponentTypes">
                        <vcl:configGroup name="victoryComponentType">
                            <vcl:configItem name="uniqueName" value="DataLogger"/>
                            <vcl:configItem name="type" value="DATA_LOGGER"/>
                        </vcl:configGroup>
                    </vcl:configGroup>
                </vcl:configGroup>
                <vcl:configGroup name="service">
                    <vcl:configItem name="uniqueName" value="ElectronicWarfareService"/>
                    <vcl:configItem name="startService" value="false"/>
                    <vcl:configGroup name="victoryComponentTypes">
                        <vcl:configGroup name="victoryComponentType">
                            <vcl:configItem name="uniqueName" value="ElectronicWarfare"/>
                            <vcl:configItem name="type" value="ELECTRONIC_WARFARE"/>
                        </vcl:configGroup>
                    </vcl:configGroup>
                </vcl:configGroup>
            </vcl:configGroup>
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.6"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/NewSharedProcessingUnit/sharedProcessingUnit"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
        <vcl:configGroup type="GENERIC_END_NODE" name="soapComponent">
            <vcl:configItem name="autodiscoveryEnabled" value="true"/>
            <vcl:configItem name="dateTime" value="2013-10-31T09:06:12Z"/>
            <vcl:configItem name="displayBlackoutEnabled" value="false"/>
            <vcl:configItem name="hostname" value="mfocs"/>
            <vcl:configGroup name="ethernetInterfaces">
                <vcl:configGroup name="ethernetInterface">
                    <vcl:configItem name="interfaceName" value="eth0"/>
                    <vcl:configItem name="uniqueName" value="5b5dfeea-1955-11e3-9a3b-f23c91aec08f"/>
                    <vcl:configItem name="macAddress" value="ff-1b-ac-00-ff-ff"/>
                    <vcl:configItem name="dhcpv4Enabled" value="false"/>
                    <vcl:configItem name="dhcpv6Enabled" value="false"/>
                    <vcl:configGroup name="staticIpConfigurations">
                        <vcl:configGroup name="staticIpConfiguration">
                            <vcl:configItem name="uniqueName" value="10-50-50-120"/>
                            <vcl:configItem name="address" value="10.50.50.120"/>
                            <vcl:configItem name="subnet" value="255.255.255.0"/>
                            <vcl:configItem name="broadcast" value="10.50.50.255"/>
                            <vcl:configItem name="gateway" value="10.50.50.1"/>
                        </vcl:configGroup>
                    </vcl:configGroup>
                    <vcl:configGroup name="autoIpConfigurations"/>
                </vcl:configGroup>                
            </vcl:configGroup>
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.7"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/NewSharedProcessingUnit/genericEndNode"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
        <vcl:configGroup type="HEALTH_PUBLISHING" name="soapComponent">
            <vcl:configItem name="faultUpdatePeriod" value="1000"/>
            <vcl:configItem name="statusEnabled" value="true"/>
            <vcl:configItem name="statusUpdatePeriod" value="5000"/>
            <vcl:configGroup name="dataTransportConfigurations">
                <vcl:configGroup name="transportConfiguration">
                    <vcl:configItem name="uniqueName" value="spuHealthUri"/>
                    <vcl:configItem name="uri" value="multicast://239.192.1.1:10155"/>
                </vcl:configGroup>
            </vcl:configGroup>
            <vcl:configGroup name="enabledFaultSeverityLevels">
                <vcl:configItem name="enabledFaultSeverityLevel" value="EMERGENCY"/>
                <vcl:configItem name="enabledFaultSeverityLevel" value="ALERT"/>
                <vcl:configItem name="enabledFaultSeverityLevel" value="CRITICAL"/>
                <vcl:configItem name="enabledFaultSeverityLevel" value="ERROR"/>
                <vcl:configItem name="enabledFaultSeverityLevel" value="WARNING"/>
            </vcl:configGroup>
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.7"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/NewSharedProcessingUnit/healthPublishing"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
        <vcl:configGroup type="VERSION_INFORMATION" name="soapComponent">
            <vcl:configItem name="interfaceStandardVersion" value="1.7"/>
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.4"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/NewSharedProcessingUnit/versionInformation"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
        <vcl:configGroup type="CONFIGURATION" name="soapComponent">
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.6"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/NewSharedProcessingUnit/configuration"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
    </vcl:configGroup>
    <vcl:configGroup type="DATA_LOGGER" name="DataLogger">
        <vcl:configItem name="announcementEnabled" value="false"/>
        <vcl:configItem name="interfaceId" value="60"/>
        <vcl:configGroup type="CONFIGURATION" name="soapComponent">
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.6"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/DataLogger/configuration"/>
                </vcl:configGroup>
            </vcl:configGroup>
        </vcl:configGroup>
        <vcl:configGroup type="DATA_LOGGER" name="soapComponent">
            <vcl:configItem name="overwriteEnabled" value="false"/>
            <vcl:configGroup name="maximumLogSize">
                <vcl:configItem name="size" value="200"/>
                <vcl:configItem name="units" value="MB"/>
            </vcl:configGroup>
            <vcl:configGroup name="ports">
                <vcl:configGroup name="port">
                    <vcl:configItem name="portStandardVersion" value="1.7"/>
                    <vcl:configItem name="uri" 
                        value="http://10.50.50.120:8080/DataLogger/dataLogger"/>
                </vcl:configGroup>
            </vcl:configGroup>
            <vcl:configGroup name="streams">
                <vcl:configGroup name="stream">
                    <vcl:configItem name="uniqueName" value="DbhSpuHealth"/>
                    <vcl:configItem name="uri" value="239.192.1.1:10100"/>
                    <vcl:configGroup name="streamType">
                        <vcl:configItem name="healthStream" value="syslog"/>
                    </vcl:configGroup>
                </vcl:configGroup>
                <vcl:configGroup name="stream">
                    <vcl:configItem name="uniqueName" value="PositionHealth"/>
                    <vcl:configItem name="uri" value="239.192.1.1:10110"/>
                    <vcl:configGroup name="streamType">
                        <vcl:configItem name="healthStream" value="syslog"/>
                    </vcl:configGroup>
                </vcl:configGroup>
                <vcl:configGroup name="stream">
                    <vcl:configItem name="uniqueName" value="PositionData"/>
                    <vcl:configItem name="uri" value="239.192.1.1:10111"/>
                    <vcl:configGroup name="streamType">
                        <vcl:configGroup name="vdmStream">
                            <vcl:configItem name="vdmType" value="POSITION"/>
                        </vcl:configGroup>
                    </vcl:configGroup>
                </vcl:configGroup>
                <vcl:configGroup name="stream">
                    <vcl:configItem name="uniqueName" value="OrientationHealth"/>
